#config.yaml
hyperparameters:
  model_name: resnet18
  input_dim: 784
  hidden_dim: 400
  output_dim: 10
  batch_size: 64
  epochs: 5
  num_classes: 10
  seed: 42

optimizer:
  _target_: torch.optim.Adam
  lr: 1e-3
  betas: [0.9, 0.999]
  eps: 1e-8
  weight_decay: 0