#config.yaml
hyperparameters:
  input_dim: 784
  hidden_dim: 400
  output_dim: 10
  batch_size: 100
  epochs: 20
  seed:

optimizer:
  _target_: torch.optim.Adam
  lr: 1e-3
  betas: [0.9, 0.999]
  eps: 1e-8
  weight_decay: 0