steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/animals-artifacts/animal_train_gpu',
    '-f',
    'dockerfiles/train_gpu.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/animals-artifacts/animal_train_gpu'
  ]
  - name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy to Cloud Run'
  args: [
    'run',
    'deploy',
    'animal-classify-app',
    '--image',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/animals-artifacts/animals_classification',
    '--region',
    'europe-west1',
    '--platform',
    'managed',
  ]
options:
  logging: CLOUD_LOGGING_ONLY